{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Giá hiên tại",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT avg_price \r\nFROM bitcoin_prices_gold \r\nORDER BY window_start DESC \r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Cao nhất 24h qua",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT max(max_price) FROM bitcoin_prices_gold WHERE window_start >= now() - INTERVAL 24 HOUR"
    }
   ]
  },
  {
   "title": "Thấp nhất 24h qua",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT min(min_price) FROM bitcoin_prices_gold WHERE window_start >= now() - INTERVAL 24 HOUR"
    }
   ]
  },
  {
   "title": "Biến động giá",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 1, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    window_start AS time,\r\n    avg_price AS \"Giá BTC\",\r\n    max_price AS \"Đỉnh\",\r\n    min_price AS \"Đáy\"\r\nFROM bitcoin_prices_gold\r\nWHERE $__timeFilter(window_start)\r\nORDER BY window_start ASC"
    }
   ]
  },
  {
   "title": "Lưu lượng xử lý",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    window_start AS time,\r\n    countMerge(total_trades) AS \"Số Events/Phút\"\r\nFROM bitcoin_prices_gold\r\nWHERE $__timeFilter(window_start)\r\nGROUP BY window_start\r\nORDER BY window_start ASC"
    }
   ]
  }
 ]
}